version: '3.8'

# Local deployment using Podman
# Includes Milvus, MCP Server, and A2A Agent

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_network

  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_network

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.6.9
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - rag_network

  mcp-server:
    container_name: rag-mcp-server
    build:
      context: ../..
      dockerfile: deployment/local/Containerfile.mcp
    environment:
      - WATSONX_API_KEY=${WATSONX_API_KEY}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - WATSONX_URL=${WATSONX_URL:-https://us-south.ml.cloud.ibm.com}
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - MILVUS_COLLECTION_NAME=${MILVUS_COLLECTION_NAME:-rag_knowledge_base}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-ibm/slate-125m-english-rtrvr}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-384}
      - LLM_MODEL=${LLM_MODEL:-ibm/granite-13b-chat-v2}
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8000:8000"
    depends_on:
      - milvus
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  a2a-agent:
    container_name: rag-a2a-agent
    build:
      context: ../..
      dockerfile: deployment/local/Containerfile.a2a
    environment:
      - WATSONX_API_KEY=${WATSONX_API_KEY}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - WATSONX_URL=${WATSONX_URL:-https://us-south.ml.cloud.ibm.com}
      - MCP_SERVER_URL=http://mcp-server:8000
      - A2A_AGENT_ID=${A2A_AGENT_ID:-rag-agent}
      - A2A_AGENT_NAME=${A2A_AGENT_NAME:-RAG Knowledge Agent}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    ports:
      - "8001:8001"
    depends_on:
      - mcp-server
    networks:
      - rag_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  data-loader:
    container_name: rag-data-loader
    build:
      context: ../..
      dockerfile: deployment/local/Containerfile.loader
    environment:
      - WATSONX_API_KEY=${WATSONX_API_KEY}
      - WATSONX_PROJECT_ID=${WATSONX_PROJECT_ID}
      - WATSONX_URL=${WATSONX_URL:-https://us-south.ml.cloud.ibm.com}
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - MILVUS_COLLECTION_NAME=${MILVUS_COLLECTION_NAME:-rag_knowledge_base}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-ibm/slate-125m-english-rtrvr}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-384}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - milvus
    networks:
      - rag_network
    restart: "no"

volumes:
  etcd_data:
    driver: local
  minio_data:
    driver: local
  milvus_data:
    driver: local

networks:
  rag_network:
    driver: bridge

# Made with Bob